CREATE OR REPLACE VIEW mart_payment_trace AS
SELECT
    payment_id,
    transaction_id,
    account_id,
    merchant_id,
    merchant_name,
    merchant_category,
    transaction_date,
    close_date,
    transaction_type,
    transaction_status,
    transaction_currency,
    transaction_currency AS currency,
    gross_minor_units,
    gross_minor_units AS expected_gross_minor_units,
    term_valid_from,
    term_valid_to,
    fee_rate_bps,
    settlement_sla_days,
    expected_settlement_date,
    expected_fee_minor_units,
    expected_settled_minor_units,
    settlement_id,
    actual_settlement_date,
    settlement_currency,
    settlement_status,
    recorded_fee_minor_units,
    recorded_settled_minor_units,
    recorded_gross_minor_units,
    fee_delta_minor_units,
    days_overdue,
    primary_reason,
    exception_reasons,
    is_missing,
    is_currency_mismatch,
    is_amount_mismatch,
    is_fee_mismatch,
    is_late,
    is_disputed,
    is_sla_breach,
    is_match,
    fraud_flag_id,
    fraud_reason,
    fraud_is_resolved,
    fraud_resolved_date,
    'payment_trace' AS lineage_query_id,
    'int_settlement_reconciliation' AS lineage_model
FROM int_settlement_reconciliation;
